name: Docker Image CI

on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract release version
      id: extract_version
      run: echo "::set-output name=tag::${GITHUB_REF##*/}"

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/wiki-engine:${{ steps.extract_version.outputs.tag }}

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}/wiki-engine:${{ steps.extract_version.outputs.tag }}
