name: Docker Image CI

on:
  release:
    types:
      - created

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract release version
      id: extract_version
      run: echo "::set-output name=tag::${GITHUB_REF##*/}"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}/wiki-engine:${{ steps.extract_version.outputs.tag }}

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository }}/wiki-engine:${{ steps.extract_version.outputs.tag }}
